### ISSUE TITLE
podspec issue

### ISSUE THREAD

**Issue by ExoticObjects** [gonzalezreal/ReadingList#10]
Hi,

Running pod --verbose install on the project generates this error:

`OpenSSL::SSL::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

Changing a line in the podspec from this:

`pod 'Overcoat', :podspec => 'https://raw.github.com/gonzalezreal/Overcoat/master/Overcoat.podspec'`

to this:

`pod 'Overcoat'`

fixes the issue.

**Comment by gonzalezreal** [comment]
@ExoticObjects Thanks for reporting the issue.
